#!/bin/bash

# generates the sources for src/plugins/*.c without gnu make
FILENAME="world_sources.mk"
SOURCESDIR="src/plugins"
echo "# Automatically generated by configure_all.sh" > $FILENAME
echo "WORLD_SOURCES = \\" >> $FILENAME

plugin_sources=$(find $SOURCESDIR -name '*.c')
total=$(echo "$plugin_sources" | wc -l)

count=0
for source in $plugin_sources; do
    count=$((count + 1))
    # Add a backslash at EOL unless last
    if [ "$count" -eq "$total" ]; then
        echo "    $source" >> "$FILENAME"
    else
        echo "    $source \\" >> "$FILENAME"
    fi
done
echo "" >> $FILENAME

# attempt to build
autoreconf -i && \
cd build && \
../configure
